name: Locust Load Test

on:
  pull_request:
    branches: [ main ]
    
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Load Test
        uses: apardo04/locust-github-action@master
        with:
          LOCUSTFILE: "locustfile.py"
          URL:  "https://live-chris-perry-test.pantheon.io"
          USERS: "5"
          RATE: "5"
          RUNTIME: "10s"
